# Header
menu:
  About: /#about
  Routes: /routes.html
  Team: /#team
  Blog: //blog.trackfellas.com
  Sign up: /#signup
  Get in touch: /#contact
rss: /atom.xml

# Content
fancybox: false

# Sidebar

# Miscellaneous
google_analytics: false
favicon: /favicon.png
twitter: trackfellas
google_plus:
fb_admins:
fb_app_id:
