# Header
menu:
  About: /#about
  Routes: /routes.html
  Team: /#team
  Blog: /#blog
  Sign up: /#signup
  Get in touch: /#contact
rss: /atom.xml

# Content
fancybox: false

# Sass
node_sass:
  file: themes/trackfellas/source/css/app.scss
  outputStyle: compressed
  precision: 5
  sourceComments: false

# Miscellaneous
google_analytics: true
favicon: /favicon.ico
twitter: trackfellas
google_plus: https://plus.google.com/+Trackfellas
fb_admins:
fb_app_id:
